### ISSUE TITLE
Adding Multi-Zone Support for LIFX Z Strip

### ISSUE THREAD

**Issue by jlwin** [foxthefox/ioBroker.lifx#11]
Hi there, 

I would really appreciate the ability to change the color of my multi zone LIFX Z LED strip.
The LIFX Z Strip has 8 individually addressable color zones per meter. The standard kit comes in a 2m version and is extendable up to 10m.

The zones should be addressable via the multi-zone selector via the API as described here:
https://api.developer.lifx.com/docs/selectors#multi-zone-selectors
I am owning a 2m version of this strip and will be happy to assist and help testing this feature.

Is it possible to have this feature integrated? 

Thanks a lot in advance, 
Jean-Luc 
(GER, ENG)

**Comment by foxthefox** [comment]
Indeed it would be a nice extension of the adapter and I have checked the lifx-package which I have as dependency. Unfortunately this package does not have this function at that time. Maybe I have to switch to another library or to find out how these libraries are developed. For sure it will take some time.

Best regards
Klaus

**Comment by foxthefox** [comment]
Hi Jean-Luc,

ich habe eine andere Bibliothek gefunden und den Adapter um zonen erweitert.
Die version 2.0.0 kann von github installiert werden.
Bitte testen und berichten.

Gruß
Klaus

PS. debug mode und logs helfen mir ungemein bei der fehlersuche

**Comment by foxthefox** [comment]
@jlwin 
Kannst du bitte testen?
