### ISSUE TITLE
Adapter is crashing

### ISSUE THREAD

**Issue by age-77** [foxthefox/ioBroker.lifx#112]
lifx.0 | 2022-12-07 21:12:48.332 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
lifx.0 | 2022-12-07 21:12:48.330 | info | terminating
lifx.0 | 2022-12-07 21:12:48.329 | info | cleaned everything up...
lifx.0 | 2022-12-07 21:12:48.322 | error | Cannot read properties of null (reading 'label')
lifx.0 | 2022-12-07 21:12:48.321 | error | TypeError: Cannot read properties of null (reading 'label') at /opt/iobroker/node_modules/iobroker.lifx/main.js:279:47 at Client.<anonymous> (/opt/iobroker/node_modules/node-lifx/lib/lifx/light.js:127:14) at Client.<anonymous> (/opt/iobroker/node_modules/node-lifx/lib/lifx/client.js:316:24) at Array.forEach (<anonymous>) at Client.processMessageHandlers (/opt/iobroker/node_modules/node-lifx/lib/lifx/client.js:287:24) at Client.<anonymous> (/opt/iobroker/node_modules/node-lifx/lib/lifx/client.js:145:10) at Socket.emit (node:events:513:28) at UDP.onMessage [as onmessage] (node:dgram:922:8)
lifx.0 | 2022-12-07 21:12:48.319 | error | uncaught exception: Cannot read properties of null (reading 'label')
lifx.0 | 2022-12-07 21:12:48.316 | debug | Error: No LIFX response in time

**Comment by foxthefox** [comment]
Sorry für die späte Antwort, war im Urlaub. Werde mir das Problem dieses WE mal anschauen

**Comment by foxthefox** [comment]
habe eine Version 1.0.2 auf github erstellt, bitte testen und berichten.
