### ISSUE TITLE
Update stable version in repo to 0.1.0

### ISSUE THREAD

**Issue by GermanBluefox** [foxthefox/ioBroker.lifx#15]
# Think about update stable version to 0.1.0
**Version**: stable=**0.0.5** (752 days old) => latest=**0.1.0** (409 days old)
**Installs**: stable=**46** (53.49%), latest=**37** (43.02%), total=**86**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L637)

**Comment by foxthefox** [comment]
done with
ioBroker/ioBroker.repositories#659
