### ISSUE TITLE
Several lights are no longer recognized

### ISSUE THREAD

**Issue by SvenM74** [foxthefox/ioBroker.lifx#168]
Several lights are no longer recognized. All GU10 and al A19. This hast been working for years without any problems. Mini D and Z is detecteted correctly. Latest adapter version is installed.

**Comment by foxthefox** [comment]
that is strange hence i have not changed anything in the code or the version of the lifx-library.
the only change was related to translation and using an additional library for development.

Is there any lamp recognized?

**Comment by SvenM74** [comment]
Yes, tow are recognized. One mini D and the Z

**Comment by foxthefox** [comment]
I fresh adapter installation right now was discovering A19, GU10 and Original 1000 and mini (all the ones which I own).
That what was expected.
BTW. my environment js-controller 4.0.23 and lifx 1.0.3

**Comment by SvenM74** [comment]
OK, let me Test a View more this and i will come Back to you

**Comment by SvenM74** [comment]
Thanks for your help
