### ISSUE TITLE
Widgets funktionieren nicht

### ISSUE THREAD

**Issue by Azathoth88** [foxthefox/ioBroker.lifx#22]
Die zwei dargebotenen Widgets zur Visualisierung in der Vis funktionieren nicht.
Ich ziehe per Drag & Drop ein Widget in meine Vis. Erwartungsgemäß sollte dort nun ein Widget erscheinen. Das passiert allerdings nicht.
Gehe ich nun auf Liste "Aktive Widgets" wird mir allerdings dieses dargestellt. Allerdings haben die dort hinterlegten Einstellungen keinen Effekt. Das Widget bleibt also komplett unsichtbar.

Im weiteren wird mir in der Widget-Liste der Dimmer-Dialog ohne richtiges Symbol / Icon dargestellt.
Stattdessen ist ein "broken Icon" - also zerschossenes Bild dargestellt.

**Comment by foxthefox** [comment]
ist denn Metro-Widgets installiert?

**Comment by Azathoth88** [comment]
War mir nicht geläufig, dass die Metro-Widgets benötigt werden. Habe diese installiert und das Ganze funktioniert auch, nachdem der Browser-Cache gelöscht wurde. Danke für den Hinweis.
