### ISSUE TITLE
Null exception with B/W bulb

### ISSUE THREAD

**Issue by L-C-P** [foxthefox/ioBroker.lifx#23]
Hi,

"colormode" is not supported for B/W bulbs.
<img width="1414" alt="Bildschirmfoto 2020-08-01 um 20 55 33" src="https://user-images.githubusercontent.com/344139/89108547-b732b700-d439-11ea-93b7-d2e4feb01dee.png">

So the code in 110 break with a null exception. I add an extra null check. I will not create a pr for that. But maybe you can include it into your code.

`                if (dp == 'bright') {
                    adapter.getState('Bulb_' + id + '.colormode', function (err, mode) {
                        if (**mode &&** mode.val === 'white') {`

**Comment by foxthefox** [comment]
I hope it is now corrected in 1.0.1, can you please check the behaviour?

**Comment by L-C-P** [comment]
Works for me. Thank you for fixing!
