### ISSUE TITLE
No configuration

### ISSUE THREAD

**Issue by GermanBluefox** [foxthefox/ioBroker.lifx#4]
As I can see, you have no configuration for you adapter.
You can delete index.html, index_m.html and words.js from repo and define in common
noConfig: true

See here for noConfig: https://github.com/ioBroker/ioBroker/blob/master/doc/SCHEMA.md#adapter

**Comment by foxthefox** [comment]
I have set the noConfig option, but I keep the files, maybe there is something in the future.
Thanks
