### ISSUE TITLE
Error with "this" context in version 1.0

### ISSUE THREAD

**Issue by L-C-P** [foxthefox/ioBroker.lifx#52]
Hi,

there is an error in the pollLifData function. The setTimeout will not preserve the context of "this". So it should be changed into an arrow function:

async pollLifxData() {
		const lifx_interval = 30; // this.config.lifx_interval || 30;
		await this.updateDevices();
		this.log.debug('polling! lifx is alive');
		lifxTimeout = setTimeout(**() => { this.pollLifxData() }**, lifx_interval * 1000);
	}

If not, you will see updateDevice is not an method of this every 30 seconds.

**Comment by foxthefox** [comment]
thanks for the feedback, I will fix it

**Comment by foxthefox** [comment]
I hope it is now corrected in 1.0.1, can you please check the behaviour?

**Comment by L-C-P** [comment]
Works for me. Thank you for fixing!
